import traceback

import driver as driver
from selenium import webdriver
import time
from selenium.webdriver.common.by import By
driver = webdriver.Chrome(executable_path="D:\driver103\chromedriver.exe")
driver.maximize_window()
#driver.get("https://stage-cloudifytests.auth.ap-south-1.amazoncognito.com/signup?client_id=5s5aovc7epna18uoi47dkahnc1&response_type=code&scope=profile+aws.cognito.signin.user.admin+openid+email+phone&redirect_uri=https://stg.cloudifytests.io/auth")
# driver.find_element(By.XPATH, "(//input[@name='username'])[1]").send_keys("332mb")
# time.sleep(1)
# driver.find_element(By.XPATH, "(//input[@name='requiredAttributes[name]'])[1]").send_keys("331mb")
# time.sleep(1)
# driver.find_element(By.XPATH, "(//input[@type='email'])[1]").send_keys("volakoy581@storypo.com")
# time.sleep(1)
# driver.find_element(By.XPATH, "(//input[@name='password'])[1]").send_keys("Hello123#")
# time.sleep(1)
# driver.find_element(By.XPATH, "(//button[@name='signUpButton'])[1]").click()
# time.sleep(26)
# driver.find_element(By.XPATH, "//button[@name='confirm']").click()
# time.sleep(3)
# driver.find_element(By.XPATH, "//input[contains(@id,'mui')]").send_keys("331mb")
# time.sleep(3)
# driver.find_element(By.XPATH, "(//button[@tabindex='0'])[2]").click()
# #time.sleep(2)
driver.get("https://stage-cloudifytests.auth.ap-south-1.amazoncognito.com/login?client_id=5s5aovc7epna18uoi47dkahnc1&response_type=code&scope=profile+aws.cognito.signin.user.admin+openid+email+phone&redirect_uri=https://stg.cloudifytests.io/auth")
time.sleep(1)
driver.find_element(By.XPATH, "(//input[@name='username'])[2]").send_keys("1tb")
time.sleep(1)
driver.find_element(By.XPATH, "(//input[@name='password'])[2]").send_keys("Hello123#")
time.sleep(1)
driver.find_element(By.XPATH, "(//input[@name='signInSubmitButton'])[2]").click()
time.sleep(3)
#driver.find_element(By.XPATH, "//button[text()='CREATE']").click()
#time.sleep(2)
driver.find_element(By.XPATH, "(//span[text()='60gb']//following-sibling::div//button)[2]").click()
#driver.find_element(By.XPATH, "//input[contains(@id,'mui')]").send_keys("331mb")
time.sleep(3)
driver.find_element(By.XPATH, "(//input[@value='10'])[2]")
time.sleep(2)
driver.find_element(By.XPATH, "(//input[@value='1'])[1]")
time.sleep(1)
driver.find_element(By.XPATH, "(//input[@value='1'])[2]")
time.sleep(1)
driver.find_element(By.XPATH, "(//button[@type='button'])[6]").click()
time.sleep(10)
driver.find_element(By.XPATH, "//div[text()='Change']").click()
time.sleep(2)
driver.find_element(By.XPATH, "//input[@id='cardNumber']").send_keys("4242424242424242")
time.sleep(1)
driver.find_element(By.XPATH, "//input[@name='cardExpiry']").send_keys("0224")
time.sleep(1)
driver.find_element(By.XPATH, "//input[@name='cardCvc']").send_keys("424")
time.sleep(1)
driver.find_element(By.XPATH, "//input[@id='billingName']").send_keys("Demo")
time.sleep(1)
driver.find_element(By.XPATH, "//option[@value='US']").click()
time.sleep(2)
driver.find_element(By.XPATH, "//input[@id='billingAddressLine1']").send_keys("sd")
time.sleep(1)
driver.find_element(By.XPATH, "//input[@id='billingAddressLine2']").send_keys("sd")
time.sleep(1)
driver.find_element(By.XPATH, "//input[@id='billingLocality']").send_keys("sd")
time.sleep(1)
driver.find_element(By.XPATH, "//input[@id='billingPostalCode']").send_keys("70000")
time.sleep(2)
driver.find_element(By.XPATH, "//button[@type='submit']").click()
time.sleep(40)

isElement=driver.find_element(By.XPATH, "//span[text()='Cloudify']").is_displayed()
#if driver.title(By.XPATH, "//span[text()='Cloudify']"):
if isElement=='True':
    print('successfull')
#     print("error msg : this site cannot be reach")
#     time.sleep(30)
#     driver.find_element(By.XPATH, "//button[@id='reload-button']").click()
#
# isElement2=driver.find_element(By.XPATH, "//span[text()='Cloudify']")
#     driver.close()
else:
    print("this site cannot be reach")
    time.sleep(20)
    driver.refresh()
    #time.sleep(10)
    #driver.find_element(By.XPATH, "//button[@id='reload-button']").click()
    if isElement == 'True':
        driver.find_element(By.XPATH, "//span[text()='Cloudify']")
        print("successfull")
    else:
        print("Application is not loaded")
    time.sleep(10)
driver.close()
####
# try:
#     driver.find_element(By.XPATH, "//span[text()='Dashboard']").is_displayed()
#     print("successfully redirect to next page")
#
# except Exception as e:
#     traceback.print_exc()
#     print("error msg:",e)
#     time.sleep(30)
#     drver.find_element(By.XPATH, "//button[@id='reload-button']").click()
#
# finally:
#driver.close()
